name: Go

on:
  pull_request:
    branches: [ master ]

jobs:

  lint:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

  test:
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      GO111MODULE: on
      MYSQL_HOST: "127.0.0.1"
      MYSQL_PORT: "3306"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "z55HrAODZMIq"
      MYSQL_DB_NAME: "wethedevelop_account"
      REDIS_ADDR: "redis:6379"
    steps:
    - uses: actions/checkout@v2

    - uses: mirromutth/mysql-action@v1.1
      with:
        mysql database: ${{ env.MYSQL_DB_NAME }}
        mysql root password: ${{ env.MYSQL_PASSWORD }}
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...
  
    - name: Test
      run: go test -v ./test/...
